# Site settings
title: Yue Liang
header-img: img/home-bg.jpg
email: liangyue268@gmail.com
description: "A Yue Liang's blog"
baseurl: ""
url: "http://www.liangyue268.com"
twitter_username: liangyue268
github_username:  liangyue268
facebook_username:  lianngyue268
linkedin_usedname:  in/yliang9
favicon: /img/favicon.ico

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
