# Site settings
title: "Fantastic World"
header-img: img/blue.jpg
description: "A Yue Liang's blog"
baseurl: ""
url: "http://www.liangyue268.com"
twitter_username: liangyue268
github_username:  liangyue268
facebook_username:  liangyue268
linkedin_usedname:  in/yliang9
favicon: /img/favicon.ico
gems: [jekyll-paginate]

# About/contact
owner: 
  name: "Yue Liang"
  email: liangyue268@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
